### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/carbon-offset#6]
Hey Ari

Local site.
Chrome
WP 5.4

I am taking a look at the plugin and received this error message.

Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Class 'CarbonOffset\Log' not found in /Users/paaljoachimromdahl/Sites/the-dev-site.dev.cc/wp-content/plugins/carbon-offset/inc/Plugin.php on line 68
( ! ) Error: Class 'CarbonOffset\Log' not found in /Users/paaljoachimromdahl/Sites/the-dev-site.dev.cc/wp-content/plugins/carbon-offset/inc/Plugin.php on line 68
Call Stack
#	Time	Memory	Function	Location
1	0.0034	694720	{main}( )	.../plugins.php:0
2	0.2123	30457240	plugin_sandbox_scrape( )	.../plugins.php:177
3	0.2124	30459824	include( '/Users/paaljoachimromdahl/Sites/the-dev-site.dev.cc/wp-content/plugins/carbon-offset/carbon-offset.php' )	.../plugin.php:2255
4	0.2125	30465152	carbon_offset( )	.../carbon-offset.php:33
5	0.2125	30465192	CarbonOffset\Plugin->init( )	.../carbon-offset.php:31
6	0.2141	30661808	CarbonOffset\Plugin->run( )	.../Plugin.php:30

![Screen Shot 2020-05-24 at 15 42 44](https://user-images.githubusercontent.com/5323259/82755660-55205a80-9dd5-11ea-9529-1aadf853c249.png)

**Comment by aristath** [comment]
This has been fixed and an update released on w.org a few days ago
