### ISSUE TITLE
Plugin error on the settings page

### ISSUE THREAD

**Issue by abishekrsrikaanth** [wplemon/carbon-offset#9]
Getting the following errors after setting up the Cloverly API key.
Any additional setup required on the Plugin or Cloverly for this to be fixed?

![image](https://user-images.githubusercontent.com/1639302/123103951-1e8f9600-d454-11eb-83c2-8d1abfc91742.png)

**Comment by aristath** [comment]
Thank you for reporting this!
The issue was fixed and a new version will be released on .org within a few minutes.
